#!/bin/env bash

BASE_URL="https://api.themoviedb.org/3"
API_TOKEN="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0ZTk3YTM4MDc5ZTlmY2JjNWM1ZmI2ODRjY2M0MjYxYyIsInN1YiI6IjYxZjE0MTg4ZTlkYTY5MDA5NDkyNDE3YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.1wQkWzosJVfuM3eIIMnPuNtOXVTxtGfJBrhAgyJFj48"
# REQUEST="curl --request GET --url "${BASE_URL}" --header "Authorization: Bearer ${API_TOKEN}" --header 'Content-Type: application/json;charset=utf-8'"
ASSETS_FOLDER="./src/Assets"
MOVIE_POSTERS="./posters/movies"
SERIES_POSTERS="./posters/series"
# 1. Check if image folder exists
# 2. If it doesn't, make folders ./Posters/{movies,series}/
if [[ ! -d "$MOVIE_POSTERS" ]]; then
    printf "%s\n" "Creating movies folder"
    mkdir -p "$MOVIE_POSTERS"
fi
if [[ ! -d "$SERIES_POSTERS" ]]; then
    printf "%s\n" "Creating series folder"
    mkdir -p "$SERIES_POSTERS"
fi

# SERIES_LIST="$(curl -s --request GET --url "${BASE_URL}/tv/popular" --header "Authorization: Bearer ${API_TOKEN}" --header 'Content-Type: application/json;charset=utf-8' | jq ".results[].poster_path" | tr -d '"')"

# 3. Download posters
for num in {1..3}; do
    MOVIES_LIST="$(curl -s --request GET --url "${BASE_URL}/movie/popular?page=$num" --header "Authorization: Bearer ${API_TOKEN}" --header 'Content-Type: application/json;charset=utf-8' | jq ".results[].poster_path" | tr -d '"')"
    for poster in $MOVIES_LIST; do
        if [[ "$poster" -ne "null" ]]; then
            printf "Downloading %s\n" $poster
            curl -s "https://www.themoviedb.org/t/p/w600_and_h900_bestv2${poster}" -o "$MOVIE_POSTERS/$poster"
        fi
    done
done
for num in {1..3}; do
    SERIES_LIST="$(curl -s --request GET --url "${BASE_URL}/tv/popular?page=$num" --header "Authorization: Bearer ${API_TOKEN}" --header 'Content-Type: application/json;charset=utf-8' | jq ".results[].poster_path" | tr -d '"')"
    for poster in $SERIES_LIST; do
        if [[ "$poster" -ne "null" ]]; then
            printf "Downloading %s\n" $poster
            curl -s "https://www.themoviedb.org/t/p/w600_and_h900_bestv2${poster}" -o "$SERIES_POSTERS/$poster"
        fi
    done
done

# 4. Generate mosaics
#   1. Movies only
#   2. Series only
#   3. Both


